name: Main workflow

on:
  - pull_request
  - push

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use setup-ocaml
        uses: ocaml/setup-ocaml@v2

      - run: opam install menhir ounit2

      - run: opam exec -- dune build

      - run: opam exec -- dune runtest
